version: '3.7'
x-api-environment: &api-environment
  - POSTGRES_USER=hello_django
  - POSTGRES_PASSWORD=hello_django
  - POSTGRES_DB=hello_django_dev
  - DB_ENGINE=django.db.backends.postgresql
  - POSTGRES_PORT=5432
  - DATABASE_HOST=db

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/debt_book:cached
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment: *api-environment
  db:
    image: postgres:10.3-alpine
    environment: *api-environment
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/